version: '3'

services:
  app:
    image: sikansi/valorant-skins
    container_name: valorant
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "8081:8081"
    expose: 
      - 8081
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - valorant-mongodb
    networks:
      - valorant
  valorant-mongodb:
    image: mongo:latest
    container_name: valorant-mongodb
    ports:
      - 27017:27017
    expose: 
      - 27017
    networks:
      - valorant
    volumes:
      - db:/data/db
networks:
  valorant:
volumes:
  db: